export const ROUTES = {
  home: '/',
  dashboard: '/',
  signIn: '/signin',
  signUp: '/signup',
  formEdit: '/forms/:id/edit',
  formResponses: '/forms/:id/responses',
  publicForm: '/forms/:uuid',
  publicFormSuccess: '/forms/:uuid/success',
  publicFormClosed: '/forms/:uuid/closed',
  admin: '/admin',
  adminFeedbackDetail: '/admin/feedback/:id',
  settings: '/settings',
  feedback: '/feedback',
  resetPassword: '/password-recovery',
}
