#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the list of files to format
FILES=$(git diff --cached --name-only --diff-filter=ACMR)

# Check if there are any modified files
if [ -n "$FILES" ]; then
  echo "Formatting files with Prettier..."
  echo "$FILES" | xargs prettier --write --ignore-unknown

  echo "Linting files with ESLint..."
  echo "$FILES" | xargs eslint # Linting without automatic fixing

  # Check the exit code of the linter for errors
  if [ $? -ne 0 ]; then
    echo "Linting failed. Please fix the errors before committing."
    exit 1
  fi

  # Add the changes back to the index
  git add $FILES
else
  echo "No changes to format or lint."
fi